### ISSUE TITLE
Warning on npm install to upgrade version when on latest version

### ISSUE THREAD

**Issue by christensena** [MindscapeHQ/raygun4js#395]
When installing with npm (yarn) I get

`warning raygun4js@2.22.0: This version contains an issue which can break client-side functionality therefore this version has been deprecated. Please install the latest version of raygun4js.`

And yet 2.22.0 is the latest version of raygun4js according to NPM.

Also if I look up `raygun4js` on npmjs.org I can only find forks (i.e. under scopes) not the straight `raygun4js`.

We are also getting an infinite loop crashing issue that may be what the warning is about above but there is no newer version to upgrade to!

**Comment by krishnaKapadia** [comment]
Hello, we have released version 2.22.1 which solves the issue that you were experiencing. Please upgrade the `raygun4js`package to the latest version.

Cheers

**Comment by christensena** [comment]
> Hello, we have released version 2.22.1 which solves the issue that you were experiencing. Please upgrade the `raygun4js`package to the latest version.

This version (2.22.1) is still not on NPM (latest is 2.22.0 there right now) and it still has the deprecation message.
https://www.npmjs.com/package/raygun4js

**Comment by krishnaKapadia** [comment]
We are able to see 2.22.1 when we go to that page, and installing the package via command line does install 2.22.1. Are you able to confirm that running `npm install raygun4js` does install this version? It seems that the npm website may still have the old package cached.

**Comment by christensena** [comment]
As per original issue description yarn/npm install installs 2.22.0

**Comment by christensena** [comment]
OK I don't know if you've done anything (cache invalidation?) but it has come right now in terms of that page now shows 2.22.1 without the deprecation message.

**Comment by christensena** [comment]
NPM says it was published "an hour ago"
